// This file is automatically generated. Do not edit it directly.
// Last updated: 2026-01-08T16:31:32Z
// Force rebuild: 2026-01-09T10:00:00Z - Vercel cache bypass
import { createClient } from "@supabase/supabase-js";
import type { Database } from "@/integrations/supabase/types";

const SUPABASE_URL = "https://ngeltlygytupgdjiagve.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5nZWx0bHlneXR1cGdkamlhZ3ZlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjU5NzkyMjYsImV4cCI6MjA4MTU1NTIyNn0.NEWh7HshhOImDEqOqJnCF-ZJQwix2QcHyTL_a-2IE3M";

// Import the supabase client like this:
// import { supabase } from "@/lib/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
    storage: typeof window !== "undefined" ? window.localStorage : undefined,
  }
});

// Inizializza la sessione al caricamento (solo client-side)
if (typeof window !== "undefined") {
  supabase.auth.getSession().then(({ data: { session } }) => {
    if (session) {
      console.log("✅ Sessione Supabase recuperata:", session.user.id);
    } else {
      console.log("⚠️ Nessuna sessione attiva");
    }
  }).catch((error) => {
    console.error("❌ Errore recupero sessione:", error);
  });
}