// This file is automatically generated. Do not edit it directly.
// Types are generated from the Supabase database schema using the Supabase CLI.

import type { Database as DB } from "@/integrations/supabase/database.types";

// Re-export the canonical Database type (optional but handy)
export type Database = DB;

// Re-export commonly used types for convenience
export type Tables<T extends keyof DB["public"]["Tables"]> =
  DB["public"]["Tables"][T]["Row"];

export type Enums<T extends keyof DB["public"]["Enums"]> = DB["public"]["Enums"][T];

export type Functions<T extends keyof DB["public"]["Functions"]> =
  DB["public"]["Functions"][T];
