export type CespitiCalcoloInput={id:string;cliente_id:string;costo_originario:number;fondo_civilistico_iniziale:number;fondo_fiscale_iniziale:number;data_entrata_funzione:string;aliquota_civilistica_override:number|null;aliquota_fiscale_override:number|null;percentuale_deducibilita_override:number|null;categoria:{aliquota_civilistica:number;aliquota_fiscale:number;percentuale_deducibilita:number;riduzione_primo_anno_percentuale:number};movimenti:{data_movimento:string;tipo:string;importo:number}[];precedente?:{fondo_civilistico_finale:number;fondo_fiscale_finale:number}|null};
export type RigaCalcolo={cespite_id:string;cliente_id:string;base_civilistica:number;aliquota_civilistica:number;quota_civilistica:number;fondo_civilistico_finale:number;residuo_civilistico:number;base_fiscale:number;aliquota_fiscale:number;percentuale_deducibilita:number;quota_fiscale_teorica:number;quota_fiscale_deducibile:number;quota_fiscale_indeducibile:number;fondo_fiscale_finale:number;residuo_fiscale:number;snapshot:any};
const money=(n:number)=>Math.round((n+Number.EPSILON)*100)/100;
export function calcolaCespite(b:CespitiCalcoloInput,esercizio:number):RigaCalcolo{
 const fine=`${esercizio}-12-31`;let variazione=0;
 for(const m of b.movimenti.filter(x=>x.data_movimento<=fine)){const v=Number(m.importo||0);if(m.tipo==="incremento"||m.tipo==="rivalutazione")variazione+=v;if(m.tipo==="decremento"||m.tipo==="svalutazione")variazione-=v}
 const base=Math.max(0,money(Number(b.costo_originario)+variazione));const ac=b.aliquota_civilistica_override??Number(b.categoria.aliquota_civilistica);const af=b.aliquota_fiscale_override??Number(b.categoria.aliquota_fiscale);const ded=b.percentuale_deducibilita_override??Number(b.categoria.percentuale_deducibilita);const primo=new Date(b.data_entrata_funzione+"T00:00:00").getFullYear()===esercizio;const rid=primo?Number(b.categoria.riduzione_primo_anno_percentuale)/100:1;
 const fondoC=Number(b.precedente?.fondo_civilistico_finale??b.fondo_civilistico_iniziale);const fondoF=Number(b.precedente?.fondo_fiscale_finale??b.fondo_fiscale_iniziale);const disponibileC=Math.max(0,base-fondoC);const disponibileF=Math.max(0,base-fondoF);const qc=money(Math.min(disponibileC,base*ac/100*rid));const qft=money(Math.min(disponibileF,base*af/100*rid));const qfd=money(qft*ded/100);const qfi=money(qft-qfd);const fc=money(fondoC+qc),ff=money(fondoF+qft);
 return {cespite_id:b.id,cliente_id:b.cliente_id,base_civilistica:base,aliquota_civilistica:ac,quota_civilistica:qc,fondo_civilistico_finale:fc,residuo_civilistico:money(Math.max(0,base-fc)),base_fiscale:base,aliquota_fiscale:af,percentuale_deducibilita:ded,quota_fiscale_teorica:qft,quota_fiscale_deducibile:qfd,quota_fiscale_indeducibile:qfi,fondo_fiscale_finale:ff,residuo_fiscale:money(Math.max(0,base-ff)),snapshot:{costo_originario:b.costo_originario,variazione,primo_anno:primo,riduzione_primo_anno_percentuale:b.categoria.riduzione_primo_anno_percentuale}};
}