import { useEffect, useState } from "react";
import { FileSpreadsheet, Loader2, Upload } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { getSupabaseClient } from "@/lib/supabase/client";

const HEADERS = ["Tipo Cliente","Tipologia Cliente","Settore Fiscale (VERO/FALSO)","Settore Lavoro (VERO/FALSO)","Settore Consulenza (VERO/FALSO)","Ragione Sociale","Partita IVA","Codice Fiscale","Indirizzo","CAP","Città","Provincia","Email","Attivo","Note"] as const;
type Header = (typeof HEADERS)[number];
type ImportRow = Record<Header, string>;
type ParsedRow = { rowNumber: number; values: ImportRow };

function blankRow(): ImportRow { return Object.fromEntries(HEADERS.map(h => [h, ""])) as ImportRow; }
function normalizeCap(value:string){const v=value.trim();if(!v)return "";if(/^\d{1,5}$/.test(v))return v.padStart(5,"0");return v;}
function normalizeBoolean(value:string,fallback:boolean){const v=value.trim().toUpperCase();if(!v)return fallback;if(["VERO","TRUE","1","SI","SÌ"].includes(v))return true;if(["FALSO","FALSE","0","NO"].includes(v))return false;throw new Error(`valore "${value}" non valido: usare VERO oppure FALSO`);}
function validPartitaIva(value:string){if(!/^\d{11}$/.test(value))return false;let sum=0;for(let i=0;i<10;i++){let n=Number(value[i]);if(i%2===1){n*=2;if(n>9)n-=9;}sum+=n;}return(10-(sum%10))%10===Number(value[10]);}
function validCodiceFiscale(value:string){const cf=value.toUpperCase();if(!/^[A-Z0-9]{16}$/.test(cf))return false;const odd=[1,0,5,7,9,13,15,17,19,21,2,4,18,20,11,3,6,8,12,14,16,10,22,25,24,23];let sum=0;for(let i=0;i<15;i++){const c=cf[i];const base=/\d/.test(c)?Number(c):c.charCodeAt(0)-65;sum+=i%2===0?odd[base]:base;}return String.fromCharCode(65+(sum%26))===cf[15];}
function normalizeRow(row:ImportRow){row["CAP"]=normalizeCap(row["CAP"]);row["Codice Fiscale"]=row["Codice Fiscale"].trim().toUpperCase();row["Partita IVA"]=row["Partita IVA"].trim();row["Provincia"]=row["Provincia"].trim().toUpperCase();return row;}
function validateRow(row:ImportRow,n:number){const errors:string[]=[];const tipo=row["Tipo Cliente"].trim();const tipologia=row["Tipologia Cliente"].trim();const cf=row["Codice Fiscale"];const piva=row["Partita IVA"];if(!["Persona fisica","Altro"].includes(tipo))errors.push("Tipo Cliente deve essere Persona fisica oppure Altro");if(!["Interno","Esterno"].includes(tipologia))errors.push("Tipologia Cliente deve essere Interno oppure Esterno");if(!row["Ragione Sociale"].trim())errors.push("Ragione Sociale obbligatoria");if(!cf)errors.push("Codice Fiscale obbligatorio");else if(tipo==="Persona fisica"&&!validCodiceFiscale(cf))errors.push(`Codice Fiscale ${cf} formalmente non valido (carattere di controllo errato)`);else if(tipo==="Altro"&&(!/^\d{11}$/.test(cf)||!validPartitaIva(cf)))errors.push(`Codice Fiscale ${cf} della società/ente non valido`);if(piva&&!validPartitaIva(piva))errors.push(`Partita IVA ${piva} formalmente non valida (controllo checksum)`);const cap=row["CAP"];if(cap&&!/^\d{5}$/.test(cap))errors.push(`CAP "${cap}" non valido: deve contenere da 1 a 5 cifre`);const provincia=row["Provincia"];if(provincia&&provincia.length!==2)errors.push("Provincia deve contenere 2 caratteri");for(const h of ["Settore Fiscale (VERO/FALSO)","Settore Lavoro (VERO/FALSO)","Settore Consulenza (VERO/FALSO)","Attivo"] as Header[]){try{normalizeBoolean(row[h],h==="Attivo");}catch(e){errors.push(`${h}: ${e instanceof Error?e.message:String(e)}`)}}if(errors.length)throw new Error(`Riga ${n} - ${row["Ragione Sociale"].trim()||"senza nominativo"}: ${errors.join("; ")}`);}

async function downloadExcelTemplate(){const ExcelJS=await import("exceljs");const wb=new ExcelJS.Workbook();const ws=wb.addWorksheet("DATI DA IMPORTARE",{views:[{state:"frozen",ySplit:1}]});ws.addRow([...HEADERS]);const mandatory=new Set(["Tipo Cliente","Tipologia Cliente","Ragione Sociale","Codice Fiscale"]);ws.getRow(1).height=42;ws.getRow(1).eachCell(c=>{c.font={bold:true,color:{argb:"FFFFFFFF"}};c.fill={type:"pattern",pattern:"solid",fgColor:{argb:mandatory.has(String(c.value))?"FFB91C1C":"FF166534"}};c.alignment={horizontal:"center",vertical:"middle",wrapText:true};});const widths=[18,20,24,24,28,34,16,20,30,10,20,12,30,12,42];ws.columns.forEach((c,i)=>c.width=widths[i]??18);for(let r=2;r<=1001;r++){ws.getCell(r,1).dataValidation={type:"list",allowBlank:false,formulae:['"Persona fisica,Altro"']};ws.getCell(r,2).dataValidation={type:"list",allowBlank:false,formulae:['"Interno,Esterno"']};[3,4,5,14].forEach(c=>ws.getCell(r,c).dataValidation={type:"list",allowBlank:true,formulae:['"VERO,FALSO"']});[7,8,10].forEach(c=>ws.getCell(r,c).numFmt="@");}ws.autoFilter={from:"A1",to:"O1"};const buffer=await wb.xlsx.writeBuffer();const blob=new Blob([buffer],{type:"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"});const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download="Template_Importazione_Clienti_SMP.xlsx";document.body.appendChild(a);a.click();a.remove();URL.revokeObjectURL(url);}
async function readExcelRows(file:File):Promise<ParsedRow[]>{const ExcelJS=await import("exceljs");const wb=new ExcelJS.Workbook();await wb.xlsx.load(await file.arrayBuffer());const ws=wb.getWorksheet("DATI DA IMPORTARE")??wb.worksheets[0];if(!ws)throw new Error("Il file Excel non contiene fogli");const headers=HEADERS.map((_,i)=>ws.getRow(1).getCell(i+1).text.trim());if(headers.join("|")!==HEADERS.join("|"))throw new Error("Le intestazioni Excel non corrispondono al template");const out:ParsedRow[]=[];for(let n=2;n<=ws.rowCount;n++){const values=blankRow();HEADERS.forEach((h,i)=>values[h]=ws.getRow(n).getCell(i+1).text.trim());if(!HEADERS.every(h=>!values[h]))out.push({rowNumber:n,values:normalizeRow(values)});}return out;}
async function readCsvRows(file:File):Promise<ParsedRow[]>{const Papa=(await import("papaparse")).default;const text=await file.text();const parsed=Papa.parse<string[]>(text,{skipEmptyLines:"greedy",delimiter:"",delimitersToGuess:[";",",","\t","|"]});if(parsed.errors.length)throw new Error(`CSV non valido: ${parsed.errors.map(e=>e.message).join("; ")}`);const matrix=parsed.data;if(!matrix.length)throw new Error("CSV vuoto");const headers=matrix[0].map(v=>String(v??"").replace(/^\uFEFF/,"").trim());if(headers.join("|")!==HEADERS.join("|"))throw new Error(`Intestazioni CSV non valide. Separatore rilevato: ${parsed.meta.delimiter||"non riconosciuto"}`);return matrix.slice(1).flatMap((source,i)=>{const values=blankRow();HEADERS.forEach((h,j)=>values[h]=String(source[j]??"").trim());if(HEADERS.every(h=>!values[h]))return[];return[{rowNumber:i+2,values:normalizeRow(values)}];});}
async function readRows(file:File){if(/\.xlsx$/i.test(file.name))return readExcelRows(file);if(/\.csv$/i.test(file.name))return readCsvRows(file);throw new Error("Formato non supportato: usare .xlsx o .csv");}
function errorText(value:unknown){if(value instanceof Error)return value.message;if(typeof value==="string")return value;try{return JSON.stringify(value)}catch{return String(value)}}

export function ClientiImportTemplateEnhancer(){const[open,setOpen]=useState(false);const[file,setFile]=useState<File|null>(null);const[busy,setBusy]=useState(false);const[message,setMessage]=useState("");const[errors,setErrors]=useState<string[]>([]);useEffect(()=>{const fn=(e:MouseEvent)=>{const b=(e.target as Element|null)?.closest("button");if(b?.textContent?.trim()!=="Importa Excel/CSV")return;e.preventDefault();e.stopPropagation();setFile(null);setMessage("");setErrors([]);setOpen(true)};window.addEventListener("click",fn,true);return()=>window.removeEventListener("click",fn,true)},[]);
const handleImport=async()=>{if(!file||busy)return;setBusy(true);setMessage("");setErrors([]);try{const rows=await readRows(file);if(!rows.length)throw new Error("Il file non contiene righe da importare");const validationErrors:string[]=[];for(const r of rows){try{validateRow(r.values,r.rowNumber)}catch(e){validationErrors.push(errorText(e))}}if(validationErrors.length){setMessage(`0 clienti importati · ${validationErrors.length} righe con errore`);setErrors(validationErrors);return;}const supabase=getSupabaseClient();const{data:{session},error:sessionError}=await supabase.auth.getSession();if(sessionError)throw sessionError;if(!session?.access_token)throw new Error("Sessione non valida: effettuare nuovamente il login");let imported=0,duplicates=0;const importErrors:string[]=[];for(const item of rows){const row=item.values;const fiscal=row["Settore Fiscale (VERO/FALSO)"];const lavoro=row["Settore Lavoro (VERO/FALSO)"];const consulenza=row["Settore Consulenza (VERO/FALSO)"];const noSector=!fiscal.trim()&&!lavoro.trim()&&!consulenza.trim();const payload={tipo_cliente:row["Tipo Cliente"],tipologia_cliente:row["Tipologia Cliente"],ragione_sociale:row["Ragione Sociale"].trim(),codice_fiscale:row["Codice Fiscale"],partita_iva:row["Partita IVA"]||null,indirizzo:row["Indirizzo"].trim()||null,cap:normalizeCap(row["CAP"])||null,citta:row["Città"].trim()||null,provincia:row["Provincia"]||null,email:row["Email"].trim()||null,settore_fiscale:noSector?true:normalizeBoolean(fiscal,false),settore_lavoro:normalizeBoolean(lavoro,false),settore_consulenza:normalizeBoolean(consulenza,false),attivo:normalizeBoolean(row["Attivo"],true),cliente:true,note:row["Note"].trim()||null};try{const response=await fetch("/api/clienti/create",{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${session.access_token}`},body:JSON.stringify(payload)});let result:any={};try{result=await response.json()}catch{}if(response.status===409){duplicates++;continue}if(!response.ok)throw new Error([result?.error,result?.details,result?.code].filter(Boolean).join(" - ")||`HTTP ${response.status}`);imported++;}catch(e){importErrors.push(`Riga ${item.rowNumber} - ${row["Ragione Sociale"]}: ${errorText(e)}`)}}setMessage(`${imported} clienti importati${duplicates?` · ${duplicates} duplicati saltati`:""}${importErrors.length?` · ${importErrors.length} righe con errore`:""}`);setErrors(importErrors);if(imported>0&&!importErrors.length)window.setTimeout(()=>window.location.reload(),1000);}catch(e){setErrors([errorText(e)])}finally{setBusy(false)}};
return <Dialog open={open} onOpenChange={v=>{if(busy)return;setOpen(v);if(!v){setFile(null);setMessage("");setErrors([])}}}><DialogContent className="max-w-3xl"><DialogHeader><DialogTitle className="flex items-center gap-2"><FileSpreadsheet className="h-5 w-5"/>Importazione Clienti da Excel/CSV</DialogTitle><DialogDescription>Carica il template Excel oppure un CSV. Prima dell'import vengono controllati tutti i dati, compresi Codice Fiscale, Partita IVA e CAP.</DialogDescription></DialogHeader><div className="space-y-5 py-2"><Button type="button" variant="outline" className="w-full" disabled={busy} onClick={()=>void downloadExcelTemplate()}><Upload className="mr-2 h-4 w-4"/>Scarica Template Excel</Button><div className="space-y-2"><Label htmlFor="clienti-import-file">File da importare</Label><Input id="clienti-import-file" type="file" accept=".xlsx,.csv" disabled={busy} onChange={e=>{setFile(e.target.files?.[0]??null);setMessage("");setErrors([])}}/>{file&&<p className="text-sm text-muted-foreground">Selezionato: <strong>{file.name}</strong></p>}</div>{message&&<div className="rounded-md border border-green-200 bg-green-50 p-3 text-sm text-green-800">{message}</div>}{errors.length>0&&<div className="max-h-64 overflow-auto rounded-md border border-red-200 bg-red-50 p-3 text-sm text-red-800"><p className="mb-2 font-semibold">Errori rilevati ({errors.length})</p><ol className="list-decimal space-y-1 pl-5">{errors.map((e,i)=><li key={i}>{e}</li>)}</ol></div>}</div><DialogFooter><Button type="button" variant="outline" disabled={busy} onClick={()=>setOpen(false)}>Annulla</Button><Button type="button" disabled={!file||busy} onClick={handleImport}>{busy&&<Loader2 className="mr-2 h-4 w-4 animate-spin"/>}{busy?"Verifica e importazione...":"Importa file"}</Button></DialogFooter></DialogContent></Dialog>;}
