import { useEffect, useState } from "react";
import { ArrowLeft, Pencil, Plus, Save, X } from "lucide-react";
import { useRouter } from "next/router";
import { getSupabaseClient } from "@/lib/supabase/client";
import { getStudioId } from "@/lib/getStudioId";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { useToast } from "@/hooks/use-toast";

type Categoria={id?:string;codice:string;descrizione:string;natura:"materiale"|"immateriale";aliquota_civilistica:number;aliquota_fiscale:number;durata_anni:string;percentuale_deducibilita:number;riduzione_primo_anno_percentuale:number;conto_costo:string;conto_ammortamento:string;conto_fondo:string;attiva:boolean;note:string};
const vuota:Categoria={codice:"",descrizione:"",natura:"materiale",aliquota_civilistica:0,aliquota_fiscale:0,durata_anni:"",percentuale_deducibilita:100,riduzione_primo_anno_percentuale:50,conto_costo:"",conto_ammortamento:"",conto_fondo:"",attiva:true,note:""};

export default function CategorieCespiti(){
 const router=useRouter(),{toast}=useToast(); const [studioId,setStudioId]=useState(""); const [rows,setRows]=useState<Categoria[]>([]); const [form,setForm]=useState<Categoria>(vuota); const [open,setOpen]=useState(false); const [saving,setSaving]=useState(false);
 useEffect(()=>{void load();},[]);
 async function load(){try{const sid=await getStudioId();if(!sid)throw new Error("Studio non disponibile");setStudioId(sid);const {data,error}=await (getSupabaseClient() as any).from("tbcespiti_categorie").select("*").eq("studio_id",sid).order("descrizione");if(error)throw error;setRows((data||[]).map((x:any)=>({...x,durata_anni:x.durata_anni?String(x.durata_anni):"",note:x.note||"",conto_costo:x.conto_costo||"",conto_ammortamento:x.conto_ammortamento||"",conto_fondo:x.conto_fondo||""})));}catch(e:any){toast({title:"Errore",description:e.message,variant:"destructive"});}}
 function edit(r:Categoria){setForm({...r});setOpen(true)} function nuovo(){setForm({...vuota});setOpen(true)}
 async function save(){if(!form.codice.trim()||!form.descrizione.trim())return toast({title:"Dati mancanti",description:"Codice e descrizione sono obbligatori.",variant:"destructive"});try{setSaving(true);const payload={studio_id:studioId,codice:form.codice.trim().toUpperCase(),descrizione:form.descrizione.trim(),natura:form.natura,aliquota_civilistica:Number(form.aliquota_civilistica),aliquota_fiscale:Number(form.aliquota_fiscale),durata_anni:form.durata_anni?Number(form.durata_anni):null,percentuale_deducibilita:Number(form.percentuale_deducibilita),riduzione_primo_anno_percentuale:Number(form.riduzione_primo_anno_percentuale),conto_costo:form.conto_costo||null,conto_ammortamento:form.conto_ammortamento||null,conto_fondo:form.conto_fondo||null,attiva:form.attiva,note:form.note||null};let q:any=(getSupabaseClient() as any).from("tbcespiti_categorie");const {error}=form.id?await q.update(payload).eq("id",form.id):await q.insert(payload);if(error)throw error;toast({title:"Salvato",description:"Categoria cespite aggiornata."});setOpen(false);await load();}catch(e:any){toast({title:"Errore",description:e.message,variant:"destructive"});}finally{setSaving(false)}}
 return <div className="container mx-auto p-6 space-y-6"><div className="flex items-center justify-between"><div><h1 className="text-3xl font-bold">Categorie cespiti</h1><p className="text-muted-foreground">Parametri civilistici e fiscali dello studio</p></div><div className="flex gap-2"><Button variant="outline" onClick={()=>router.push("/cespiti")}><ArrowLeft className="mr-2 h-4 w-4"/>Cespiti</Button><Button onClick={nuovo}><Plus className="mr-2 h-4 w-4"/>Nuova categoria</Button></div></div>
 <Card><CardContent className="pt-6 overflow-x-auto"><table className="w-full text-sm"><thead><tr className="border-b text-left"><th className="p-2">Codice</th><th>Descrizione</th><th>Natura</th><th className="text-right">Aliq. civ.</th><th className="text-right">Aliq. fisc.</th><th className="text-right">Deduc.</th><th>Stato</th><th></th></tr></thead><tbody>{rows.map(r=><tr key={r.id} className="border-b"><td className="p-2 font-medium">{r.codice}</td><td>{r.descrizione}</td><td className="capitalize">{r.natura}</td><td className="text-right">{r.aliquota_civilistica}%</td><td className="text-right">{r.aliquota_fiscale}%</td><td className="text-right">{r.percentuale_deducibilita}%</td><td>{r.attiva?"Attiva":"Disattiva"}</td><td className="text-right"><Button size="sm" variant="ghost" onClick={()=>edit(r)}><Pencil className="h-4 w-4"/></Button></td></tr>)}</tbody></table>{!rows.length&&<div className="py-10 text-center text-muted-foreground">Nessuna categoria configurata.</div>}</CardContent></Card>
 {open&&<div className="fixed inset-0 z-50 bg-black/40 flex items-center justify-center p-4"><Card className="w-full max-w-4xl max-h-[90vh] overflow-y-auto"><CardHeader className="flex flex-row items-center justify-between"><CardTitle>{form.id?"Modifica categoria":"Nuova categoria"}</CardTitle><Button variant="ghost" size="icon" onClick={()=>setOpen(false)}><X/></Button></CardHeader><CardContent className="grid gap-4 md:grid-cols-2">
 <div><Label>Codice *</Label><Input value={form.codice} onChange={e=>setForm({...form,codice:e.target.value})}/></div><div><Label>Descrizione *</Label><Input value={form.descrizione} onChange={e=>setForm({...form,descrizione:e.target.value})}/></div>
 <div><Label>Natura</Label><select className="w-full rounded-md border px-3 py-2" value={form.natura} onChange={e=>setForm({...form,natura:e.target.value as any})}><option value="materiale">Materiale</option><option value="immateriale">Immateriale</option></select></div><div><Label>Durata anni</Label><Input type="number" min="1" value={form.durata_anni} onChange={e=>setForm({...form,durata_anni:e.target.value})}/></div>
 <div><Label>Aliquota civilistica %</Label><Input type="number" step=".01" value={form.aliquota_civilistica} onChange={e=>setForm({...form,aliquota_civilistica:Number(e.target.value)})}/></div><div><Label>Aliquota fiscale %</Label><Input type="number" step=".01" value={form.aliquota_fiscale} onChange={e=>setForm({...form,aliquota_fiscale:Number(e.target.value)})}/></div>
 <div><Label>Deducibilità %</Label><Input type="number" step=".01" value={form.percentuale_deducibilita} onChange={e=>setForm({...form,percentuale_deducibilita:Number(e.target.value)})}/></div><div><Label>Riduzione primo anno %</Label><Input type="number" step=".01" value={form.riduzione_primo_anno_percentuale} onChange={e=>setForm({...form,riduzione_primo_anno_percentuale:Number(e.target.value)})}/></div>
 <div><Label>Conto costo cespite</Label><Input value={form.conto_costo} onChange={e=>setForm({...form,conto_costo:e.target.value})}/></div><div><Label>Conto ammortamento</Label><Input value={form.conto_ammortamento} onChange={e=>setForm({...form,conto_ammortamento:e.target.value})}/></div><div><Label>Conto fondo</Label><Input value={form.conto_fondo} onChange={e=>setForm({...form,conto_fondo:e.target.value})}/></div>
 <div className="md:col-span-2"><Label>Note</Label><Textarea value={form.note} onChange={e=>setForm({...form,note:e.target.value})}/></div><label className="flex items-center gap-2"><input type="checkbox" checked={form.attiva} onChange={e=>setForm({...form,attiva:e.target.checked})}/>Categoria attiva</label>
 <div className="md:col-span-2 flex justify-end gap-2"><Button variant="outline" onClick={()=>setOpen(false)}>Annulla</Button><Button disabled={saving} onClick={save}><Save className="mr-2 h-4 w-4"/>{saving?"Salvataggio...":"Salva"}</Button></div></CardContent></Card></div>}</div>
}