-- ELIMINAZIONE TABELLE SBAGLIATE
DROP TABLE IF EXISTS comunicazioni CASCADE;
DROP TABLE IF EXISTS eventi_agenda CASCADE;
DROP TABLE IF EXISTS scadenze CASCADE;
DROP TABLE IF EXISTS contatti CASCADE;
DROP TABLE IF EXISTS clienti CASCADE;
DROP TABLE IF EXISTS utenti CASCADE;
DROP TABLE IF EXISTS studios CASCADE;