plugins { id 'com.android.application' }

android {
    namespace 'it.studiomanagerpro.nativeapp'
    compileSdk 35

    defaultConfig {
        applicationId "it.studiomanagerpro.mobile"
        minSdk 26
        targetSdk 35
        versionCode 13
        versionName "1.13-native"
    }
}

dependencies {
}
