// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://byrdqcsrbwegfhaobpmw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ5cmRxY3NyYndlZ2ZoYW9icG13Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjU5NzY1NTQsImV4cCI6MjA4MTU1MjU1NH0.BsKrDqo-kyf0oYIx6tcCJJGpTRf5nwM9F8yhAGO9e4Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
