// This file is automatically generated. Do not edit it directly.
// Types are generated from the Supabase database schema using the Supabase CLI.

import type { Database as DB } from './database.types';

type TbutentiTable = DB['public']['Tables']['tbutenti'];

type TbutentiTableWithSystemAdmin = {
  Row: TbutentiTable['Row'] & {
    amministratore_sistema_generale: boolean;
  };
  Insert: TbutentiTable['Insert'] & {
    amministratore_sistema_generale?: boolean;
  };
  Update: TbutentiTable['Update'] & {
    amministratore_sistema_generale?: boolean;
  };
  Relationships: TbutentiTable['Relationships'];
};

export type Database = Omit<DB, 'public'> & {
  public: Omit<DB['public'], 'Tables'> & {
    Tables: Omit<DB['public']['Tables'], 'tbutenti'> & {
      tbutenti: TbutentiTableWithSystemAdmin;
    };
  };
};

// Re-export commonly used types for convenience
export type Tables<T extends keyof Database['public']['Tables']> = Database['public']['Tables'][T]['Row'];
export type Enums<T extends keyof Database['public']['Enums']> = Database['public']['Enums'][T];
export type Functions<T extends keyof Database['public']['Functions']> = Database['public']['Functions'][T];

// Project reference: ngeltlygytupgdjiagve
// Last updated: 2026-08-31 manual extension for amministratore_sistema_generale
